{
    "Dashboard": "Panel de Control",
    "Staff": "Personal",
    "Manager": "Gerente",
    "Admin": "Administrador",
    "Account Settings": "Configuración de la Cuenta",
    "Sign Out": "Cerrar Sesión",
    "Home": "Inicio",
    "Account": "Cuenta",
    "Security": "Seguridad",
    "API Credentials": "Credenciales de API",
    "SSH Keys": "Claves SSH",
    "API": "API",
    "SSH": "SSH",
    "Activity": "Actividad",
    "Logout": "Cerrar Sesión",
    "Portal": "Portal",
    "Premium Server": "Servidor Premium",
    "Free Server": "Servidor Gratuito",
    "Tutorials": "Tutoriales",
    "Discord": "Discord",
    "Server": "Servidor",
    "Console": "Consola",
    "Files": "Archivos",
    "Showing your servers": "Mostrando tus servidores",
    "Showing others' servers": "Mostrando servidores de otros",
    "You are a premium user! To redeem your customer role and access premium support, join our Discord and create a ticket.": "¡Eres un usuario premium! Para canjear tu rol de cliente y acceder a soporte premium, únete a nuestro Discord y crea un ticket.",
    "Create Free Server": "Crear Servidor Gratuito",
    "No servers found.": "No se encontraron servidores.",
    "It looks like you have no servers.": "Parece que no tienes servidores.",
    "All Rights Reserved.": "Todos los Derechos Reservados.",
    "Terms of Service": "Términos de Servicio",
    "Privacy Policy": "Política de Privacidad",
    "Create": "Crear",
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "Update": "Actualizar",
    "Back": "Atrás",
    "Close": "Cerrar",
    "Confirm": "Confirmar",
    "Yes": "Sí",
    "No": "No",
    "Submit": "Enviar",
    "View Details": "Ver Detalles",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Import": "Importar",
    "Export": "Exportar",
    "Download": "Descargar",
    "Upload": "Subir",
    "Connect": "Conectar",
    "Disconnect": "Desconectar",
    "Copy": "Copiar",
    "Refresh": "Actualizar",
    "Apply": "Aplicar",
    "Return to Login": "Volver a Iniciar Sesión",
    "Install": "Instalar",
    "Uninstall": "Desinstalar",
    "Reinstall": "Reinstalar",
    "Configure": "Configurar",
    "View": "Ver",
    "Start": "Iniciar",
    "Stop": "Detener",
    "Restart": "Reiniciar",
    "Kill": "Terminar",
    "Send": "Enviar",
    "Continue": "Continuar",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Finish": "Finalizar",
    "Reset": "Restablecer",
    "Clear": "Limpiar",
    "Select": "Seleccionar",
    "Deselect": "Deseleccionar",
    "Enable": "Habilitar",
    "Disable": "Deshabilitar",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Pending": "Pendiente",
    "Completed": "Completado",
    "Failed": "Fallido",
    "Loading": "Cargando",
    "Loading...": "Cargando...",
    "Success": "Éxito",
    "Error": "Error",
    "Warning": "Advertencia",
    "Info": "Información",
    "Online": "En Línea",
    "Offline": "Fuera de Línea",
    "Starting": "Iniciando",
    "Stopping": "Deteniendo",
    "Running": "Ejecutándose",
    "Suspended": "Suspendido",
    "Installing": "Instalando",
    "Restoring": "Restaurando",
    "Transferring": "Transfiriendo",
    "Successfully saved.": "Guardado exitosamente.",
    "Successfully updated.": "Actualizado exitosamente.",
    "Successfully deleted.": "Eliminado exitosamente.",
    "Successfully created.": "Creado exitosamente.",
    "Are you sure you want to delete this?": "¿Estás seguro de que quieres eliminar esto?",
    "This action cannot be undone.": "Esta acción no se puede deshacer.",
    "No results found.": "No se encontraron resultados.",
    "No servers found matching your search.": "No se encontraron servidores que coincidan con tu búsqueda.",
    "Searching...": "Buscando...",
    "Copied to clipboard": "Copiado al portapapeles",
    "Click to copy": "Clic para copiar",
    "Click to copy allocation(s)": "Clic para copiar asignación(es)",
    "Something went wrong.": "Algo salió mal.",
    "An error occurred.": "Ocurrió un error.",
    "Please try again later.": "Por favor, inténtalo de nuevo más tarde.",
    "Access Denied": "Acceso Denegado",
    "You do not have permission to access this page.": "No tienes permiso para acceder a esta página.",
    "Page not found": "Página no encontrada",
    "The page you are looking for does not exist.": "La página que buscas no existe.",
    "Name": "Nombre",
    "Description": "Descripción",
    "Email": "Correo Electrónico",
    "Password": "Contraseña",
    "Current Password": "Contraseña Actual",
    "New Password": "Nueva Contraseña",
    "Confirm Password": "Confirmar Contraseña",
    "Confirm New Password": "Confirmar Nueva Contraseña",
    "Username": "Nombre de Usuario",
    "Type to search...": "Escribe para buscar...",
    "Search...": "Buscar...",
    "Notes": "Notas",
    "Reason": "Razón",
    "Value": "Valor",
    "Key": "Clave",
    "Variable": "Variable",
    "Port": "Puerto",
    "IP Address": "Dirección IP",
    "Host": "Host",
    "Database": "Base de Datos",
    "Databases": "Bases de Datos",
    "This field is required": "Este campo es obligatorio",
    "Please enter a valid email address": "Por favor, introduce una dirección de correo electrónico válida",
    "Passwords do not match": "Las contraseñas no coinciden",
    "Password must be at least 8 characters": "La contraseña debe tener al menos 8 caracteres",
    "Optional": "Opcional",
    "Required": "Requerido",
    "File Manager": "Administrador de Archivos",
    "Server Info": "Información del Servidor",
    "Schedules": "Tareas Programadas",
    "Users": "Usuarios",
    "Backups": "Copias de Seguridad",
    "Network": "Red",
    "Startup": "Inicio",
    "Settings": "Ajustes",
    "Terminal": "Terminal",
    "Modpacks": "Paquetes de Mods",
    "Mods": "Mods",
    "Properties": "Propiedades",
    "World Manager": "Administrador de Mundos",
    "Google Drive Backup": "Copia de Seguridad en Google Drive",
    "Plugin manager": "Administrador de Plugins",
    "Minecraft Player Manager": "Administrador de Jugadores de Minecraft",
    "Servers": "Servidores",
    "Server Name": "Nombre del Servidor",
    "Server Description": "Descripción del Servidor",
    "Server Status": "Estado del Servidor",
    "Server Information": "Información del Servidor",
    "Server Settings": "Configuración del Servidor",
    "SFTP Details": "Detalles SFTP",
    "Debug Information": "Información de Depuración",
    "Reinstall Server": "Reinstalar Servidor",
    "Transfer Server": "Transferir Servidor",
    "Delete Server": "Eliminar Servidor",
    "Memory": "Memoria",
    "CPU": "CPU",
    "Disk": "Disco",
    "Disk Space": "Espacio en Disco",
    "Current Resource Usage": "Uso Actual de Recursos",
    "Allocated": "Asignado",
    "Used": "Usado",
    "Available": "Disponible",
    "New File": "Nuevo Archivo",
    "New Folder": "Nueva Carpeta",
    "Upload Files": "Subir Archivos",
    "File Name": "Nombre del Archivo",
    "Folder Name": "Nombre de la Carpeta",
    "Size": "Tamaño",
    "Last Modified": "Última Modificación",
    "Permissions": "Permisos",
    "Compress": "Comprimir",
    "Decompress": "Descomprimir",
    "Archive": "Archivar",
    "Extract": "Extraer",
    "Rename": "Renombrar",
    "Move": "Mover",
    "Mass Delete": "Eliminación Masiva",
    "Schedule": "Programación",
    "New Schedule": "Nueva Programación",
    "Schedule Name": "Nombre de la Programación",
    "Enabled": "Habilitado",
    "Disabled": "Deshabilitado",
    "Last Run": "Última Ejecución",
    "Next Run": "Próxima Ejecución",
    "Tasks": "Tareas",
    "New Task": "Nueva Tarea",
    "Task": "Tarea",
    "Action": "Acción",
    "Actions": "Acciones",
    "Payload": "Carga Útil",
    "Time Offset": "Desplazamiento de Tiempo",
    "Continue on Failure": "Continuar en Caso de Fallo",
    "Backup": "Copia de Seguridad",
    "Create Backup": "Crear Copia de Seguridad",
    "Backup Name": "Nombre de la Copia de Seguridad",
    "Locked": "Bloqueado",
    "Unlocked": "Desbloqueado",
    "Checksum": "Suma de Verificación",
    "Restore": "Restaurar",
    "Download Backup": "Descargar Copia de Seguridad",
    "Delete Backup": "Eliminar Copia de Seguridad",
    "Lock Backup": "Bloquear Copia de Seguridad",
    "Unlock Backup": "Desbloquear Copia de Seguridad",
    "User": "Usuario",
    "Email Address": "Dirección de Correo Electrónico",
    "Subusers": "Subusuarios",
    "New User": "Nuevo Usuario",
    "Invite User": "Invitar Usuario",
    "Grant Permissions": "Otorgar Permisos",
    "Revoke Permissions": "Revocar Permisos",
    "Select All": "Seleccionar Todo",
    "Deselect All": "Deseleccionar Todo",
    "Allocations": "Asignaciones",
    "Primary": "Primaria",
    "Make Primary": "Establecer como Primaria",
    "Alias": "Alias",
    "Assign Additional Ports": "Asignar Puertos Adicionales",
    "Startup Command": "Comando de Inicio",
    "Startup Variables": "Variables de Inicio",
    "Docker Image": "Imagen Docker",
    "Default Value": "Valor Predeterminado",
    "Billing": "Facturación",
    "Balance": "Saldo",
    "Cart": "Carrito",
    "My Plans": "Mis Planes",
    "Manage": "Gestionar",
    "Plugin": "Plugin",
    "Account Balance": "Saldo de la Cuenta",
    "PayPal": "PayPal",
    "Stripe": "Stripe",
    "Gift Card": "Tarjeta de Regalo",
    "Billing Information": "Información de Facturación",
    "Please enter the amount you would like to add": "Por favor, introduce la cantidad que deseas añadir",
    "Amount": "Cantidad",
    "Card Holder Name": "Nombre del Titular de la Tarjeta",
    "Card Number": "Número de Tarjeta",
    "Expiration Date": "Fecha de Caducidad",
    "CVV": "CVV",
    "Pay Now": "Pagar Ahora",
    "Address": "Dirección",
    "First Name": "Nombre",
    "Last Name": "Apellido",
    "City": "Ciudad",
    "Country": "País",
    "State": "Estado",
    "Province": "Provincia",
    "Postal Code": "Código Postal",
    "ZIP Code": "Código Postal",
    "Phone": "Teléfono",
    "Phone Number": "Número de Teléfono",
    "Update Billing Information": "Actualizar Información de Facturación",
    "Edit Account": "Editar Cuenta",
    "Account API": "API de Cuenta",
    "Admin Area": "Área de Administración",
    "Dark Mode": "Modo Oscuro",
    "Light Mode": "Modo Claro",
    "Gift Card Code": "Código de Tarjeta de Regalo",
    "Redeem": "Canjear",
    "Balance:": "Saldo:",
    "Current Balance:": "Saldo Actual:",
    "Checkout": "Pagar",
    "Game": "Juego",
    "Plan": "Plan",
    "Price": "Precio",
    "Billed": "Facturado",
    "Cart is empty.": "El carrito está vacío.",
    "Place Order": "Realizar Pedido",
    "Plan Name": "Nombre del Plan",
    "Total": "Total",
    "Subtotal": "Subtotal",
    "Discount": "Descuento",
    "Total Order: ": "Total del Pedido: ",
    "After clicking \"Confirm Order\", your order will be placed and the amount will be reduced from your current balance.": "Después de hacer clic en \"Confirmar Pedido\", tu pedido será realizado y la cantidad se reducirá de tu saldo actual.",
    "Discount Code": "Código de Descuento",
    "Apply Discount": "Aplicar Descuento",
    "Remove from Cart": "Eliminar del Carrito",
    "Date": "Fecha",
    "View Plans": "Ver Planes",
    "View Invoices": "Ver Facturas",
    "Extend": "Extender",
    "days for": "días por",
    "Deleted": "Eliminado",
    "Pay": "Pagar",
    "Are you sure?": "¿Estás seguro?",
    "Remove": "Eliminar",
    "Plans": "Planes",
    "Add to Cart": "Añadir al Carrito",
    "Monthly": "Mensual",
    "Yearly": "Anual",
    "Year": "Año",
    "Quarterly": "Trimestral",
    "Weekly": "Semanal",
    "Daily": "Diario",
    "One Time": "Una Vez",
    "Unlimited": "Ilimitado",
    "Days": "días",
    "Hours": "horas",
    "Minutes": "minutos",
    "CPU:": "CPU:",
    "RAM:": "RAM:",
    "Disk:": "Disco:",
    "Storage:": "Almacenamiento:",
    "Backup(s)": "Copia(s) de Seguridad",
    "Database(s)": "Base(s) de Datos",
    "Extra Ports": "Puertos Extra",
    "Slots": "Espacios",
    "Players": "Jugadores",
    "Invoice": "Factura",
    "Invoices": "Facturas",
    "Invoice Date:": "Fecha de Factura:",
    "Due Date:": "Fecha de Vencimiento:",
    "Invoice Date": "Fecha de Factura",
    "Due Date": "Fecha de Vencimiento",
    "Price:": "Precio:",
    "Status": "Estado",
    "Paid": "Pagado",
    "Unpaid": "Impagado",
    "Overdue": "Vencido",
    "Cancelled": "Cancelado",
    "Refunded": "Reembolsado",
    "Renew Plan": "Renovar Plan",
    "View Invoice": "Ver Factura",
    "Request Cancellation": "Solicitar Cancelación",
    "Renew": "Renovar",
    "Plan added to cart": "Plan añadido al carrito",
    "Your server has been created successfully, go to My Plans for more information.": "Tu servidor ha sido creado exitosamente, ve a Mis Planes para más información.",
    "Payment successful!": "¡Pago exitoso!",
    "Order placed successfully!": "¡Pedido realizado exitosamente!",
    "Balance added successfully!": "¡Saldo añadido exitosamente!",
    "Sorry. You must first remove all plans that belong to this game.": "Lo sentimos. Primero debes eliminar todos los planes que pertenecen a este juego.",
    "Sorry. You have reached a limit. You can only purchase the following amount: ": "Lo sentimos. Has alcanzado un límite. Solo puedes comprar la siguiente cantidad: ",
    "An error occurred while creating a new server.": "Ocurrió un error al crear un nuevo servidor.",
    "There is not enough balance in your account to make this purchase.": "No hay saldo suficiente en tu cuenta para realizar esta compra.",
    "Plan has been removed from your cart.": "El plan ha sido eliminado de tu carrito.",
    "There are no plans for this game.": "No hay planes para este juego.",
    "Invalid discount code.": "Código de descuento no válido.",
    "Discount code expired.": "El código de descuento ha expirado.",
    "Payment failed.": "El pago falló.",
    "Insufficient funds.": "Fondos insuficientes.",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Tomorrow": "Mañana",
    "Now": "Ahora",
    "Never": "Nunca",
    "Just now": "Justo ahora",
    "a minute ago": "hace un minuto",
    "minutes ago": "hace minutos",
    "an hour ago": "hace una hora",
    "hours ago": "hace horas",
    "a day ago": "hace un día",
    "days ago": "hace días",
    "a week ago": "hace una semana",
    "weeks ago": "hace semanas",
    "a month ago": "hace un mes",
    "months ago": "hace meses",
    "a year ago": "hace un año",
    "years ago": "hace años",
    "Page": "Página",
    "of": "de",
    "Showing": "Mostrando",
    "to": "a",
    "entries": "entradas",
    "results": "resultados",
    "First": "Primero",
    "Last": "Último",
    "Language": "Idioma",
    "Theme": "Tema",
    "Notifications": "Notificaciones",
    "Support": "Soporte",
    "Documentation": "Documentación",
    "Help": "Ayuda",
    "Contact": "Contacto",
    "About": "Acerca de",
    "Version": "Versión",
    "Copyright": "Derechos de Autor",
    "Powered by": "Impulsado por",
    "Welcome": "Bienvenido",
    "Welcome back": "Bienvenido de nuevo",
    "Hello": "Hola",
    "Goodbye": "Adiós",
    "Thank you": "Gracias",
    "Please wait...": "Por favor, espera...",
    "Processing...": "Procesando...",
    "Saving...": "Guardando...",
    "Deleting...": "Eliminando...",
    "Updating...": "Actualizando...",
    "Connecting...": "Conectando...",
    "Change IP": "Cambiar IP",
    "Server Unavailable": "Servidor No Disponible",
    "No Plans Purchased": "No Hay Planes Comprados",
    "You haven't purchased any plans yet. Explore our available plans and find the perfect one for your needs.": "Aún no has comprado ningún plan. Explora nuestros planes disponibles y encuentra el perfecto para tus necesidades.",
    "Manage your active plans and view billing information": "Administra tus planes activos y visualiza la información de facturación",
    "Choose from our wide selection di games for your server hosting": "Elige entre nuestra amplia selección de juegos para tu alojamiento de servidor",
    "Game Hosting": "Alojamiento de Juegos",
    "Not available at the moment": "No disponible en este momento",
    "Custom hosting for any game": "Alojamiento personalizado para cualquier juego",
    "If you don't find the game you're looking for, you can request cusam hosting by joining our Discord.": "Si no encuentras el juego que buscas, puedes solicitar alojamiento personalizado uniéndote a nuestro Discord.",
    "Ready a Play?": "¿Listo para Jugar?",
    "Let's create your free server in just a few steps.": "Vamos a crear tu servidor gratuito en solo unos pocos pasos.",
    "We offer a variety of server types, versions, and locations to suit your needs.": "Ofrecemos una variedad de tipos de servidor, versiones y ubicaciones para satisfacer tus necesidades.",
    "Starter": "Básico",
    "Standard": "Estándar",
    "Power": "Potente",
    "Ultra": "Ultra",
    "Unlimited Players": "Jugadores Ilimitados",
    "Unlimited Mods/Plugins": "Mods/Plugins Ilimitados",
    "Important: Read This First!": "¡Importante: Lee Esto Primero!",
    "Before creating your server, please read our guide to understand how the renewal system works. This will help you keep your server online 24/7!": "Antes de crear tu servidor, por favor, lee nuestra guía para entender cómo funciona el sistema de renovación. ¡Esto te ayudará a mantener tu servidor en línea 24/7!",
    "Read the Guide Now": "Leer la Guía Ahora",
    "Read Guide First!": "¡Leer Guía Primero!",
    "📖 Read Guide First!": "📖 ¡Leer Guía Primero!",
    "How Server Renewals Work": "Cómo Funcionan las Renovaciones del Servidor",
    "Everything you need to know!": "¡Todo lo que necesitas saber!",
    "Daily Renewal System": "Sistema de Renovación Diaria",
    "The renew system ensures your server stays online based on your activity and plan. Each plan requires a specific number of renewals every 24 hours. For example, if your plan needs 6 renewals per day, you'll need to renew it roughly every 4 hours to keep it running.": "El sistema de renovación asegura que tu servidor permanezca en línea basado en tu actividad y plan. Cada plan requiere un número específico de renovaciones cada 24 horas. Por ejemplo, si tu plan necesita 6 renovaciones al día, tendrás que renovarlo aproximadamente cada 4 horas para mantenerlo en funcionamiento.",
    "Cooldown Period": "Período de Enfriamiento",
    "There is a waiting time between each renewal, which also depends on your plan. You can only renew again after this cooldown period has passed": "Hay un tiempo de espera entre cada renovación, que también depende de tu plan. Solo puedes renovar de nuevo después de que haya pasado este período de enfriamiento.",
    "Daily Reset": "Restablecimiento Diario",
    "The daily renewal count resets at midnight (00:00 UTC), so each day you start with a fresh limit.": "El contador de renovación diaria se restablece a medianoche (00:00 UTC), por lo que cada día comienzas con un límite nuevo.",
    "Keep It Running 24/7": "Mantenlo Funcionando 24/7",
    "As long as you keep renewing on time, your server will stay online 24/7.": "Mientras sigas renovando a tiempo, tu servidor permanecerá en línea 24/7.",
    "What If I Miss a Renewal?": "¿Qué Pasa Si Me Pierdo una Renovación?",
    "If you miss a renewal, the server will be suspended, but you still have 15 days to renew it before it gets permanently deleted.": "Si te pierdes una renovación, el servidor será suspendido, pero aún tienes 15 días para renovarlo antes de que se elimine permanentemente.",
    "In no other case will your server be reset or deleted.": "En ningún otro caso tu servidor será restablecido o eliminado.",
    "Got it": "Entendido",
    "What kind of server would you like to create?": "¿Qué tipo de servidor te gustaría crear?",
    "How it Works": "Cómo Funciona",
    "Which version do you want to use?": "¿Qué versión quieres usar?",
    "Renew every": "Renovar cada",
    "Max renewals/day": "Renovaciones máx./día",
    "Where do you want your server to be hosted?": "¿Dónde quieres que se aloje tu servidor?",
    "Great location for EU customers.": "Excelente ubicación para clientes de la UE.",
    "Great location for US customers.": "Excelente ubicación para clientes de EE. UU.",
    "Disclaimer": "Descargo de Responsabilidad",
    "By creating a server, you agree to the Minecraft EULA. Please ensure you understand and accept the terms before proceeding.": "Al crear un servidor, aceptas el EULA de Minecraft. Por favor, asegúrate de entender y aceptar los términos antes de proceder.",
    "Please ensure you understand and accept the terms before proceeding.": "Por favor, asegúrate de entender y aceptar los términos antes de proceder.",
    "By creating a server, you agree to the ": "Al crear un servidor, aceptas los ",
    "You can't create more free servers. Maximum is 1 per user.": "No puedes crear más servidores gratuitos. El máximo es 1 por usuario.",
    "Get Server ID": "Obtener ID del Servidor",
    "Wiki e Guides": "Wiki y Guías",
    "Share your logs": "Compartir tus registros (logs)",
    "Analyze logs with AI": "Analizar registros (logs) con IA",
    "Players Online": "Jugadores En Línea",
    "DISK": "DISCO",
    "RAM": "RAM",
    "Recycle Bin": "Papelera de Reciclaje",
    "Create directory": "Crear directorio",
    "Upload folder": "Subir carpeta",
    "Need help managing files? Check out our ": "¿Necesitas ayuda para gestionar archivos? Echa un vistazo a nuestra ",
    "Navigation & Actions": "Navegación y Acciones",
    "Files & Folders": "Archivos y Carpetas",
    "Search & Filters": "Búsqueda y Filtros",
    "Find plugins by name or functionality": "Encuentra plugins por nombre o funcionalidad",
    "No available plugins a install.": "No hay plugins disponibles para instalar.",
    "Versions": "Versiones",
    "Options": "Opciones",
    "Find specific server settings quickly by searching their names": "Encuentra ajustes específicos del servidor rápidamente buscando sus nombres",
    "Basic server settings that every Minecraft server owner should configure": "Configuración básica del servidor que todo propietario de un servidor de Minecraft debería configurar",
    "Configura your Minecraft world generation and behavior": "Configura la generación y el comportamiento de tu mundo de Minecraft",
    "Control who can join your server and security features": "Controla quién puede unirse a tu servidor y las características de seguridad",
    "Advanced server configuration for experienced users": "Configuración avanzada del servidor para usuarios experimentados",
    "Additional server configuration options": "Opciones de configuración de servidor adicionales",
    "Player Management": "Gestión de Jugadores",
    "Player Manager": "Administrador de Jugadores",
    "No Player Selected": "Ningún Jugador Seleccionado",
    "Select a player from the list to view details and manage their data": "Selecciona un jugador de la lista para ver detalles y gestionar sus datos",
    "Some modpacks may require additional installation steps that the server cannot perform automatically.": "Algunos paquetes de mods pueden requerir pasos de instalación adicionales que el servidor no puede realizar automáticamente.",
    "Always check the modpack documentation and make sure it is compatible with your server setup.": "Comprueba siempre la documentación del paquete de mods y asegúrate de que es compatible con la configuración de tu servidor.",
    "Need help with modpack installation? Check our comprehensive guide:": "¿Necesitas ayuda con la instalación de paquetes de mods? Consulta nuestra guía completa:",
    "Browse Modpacks": "Explorar Paquetes de Mods",
    "Got it!": "¡Entendido!",
    "Search Modpacks": "Buscar Paquetes de Mods",
    "Databases Unavailable": "Bases de Datos No Disponibles",
    "Database creation is not available for this server.": "La creación de bases de datos no está disponible para este servidor.",
    "Create New Schedule": "Crear Nueva Tarea Programada",
    "Create automated tasks that run on a schedule to manage your server.": "Crea tareas automatizadas que se ejecutan según un horario para administrar tu servidor.",
    "No Schedules Found": "No Se Encontraron Tareas Programadas",
    "Create your first schedule to automate server tasks and maintenance.": "Crea tu primera tarea programada para automatizar las tareas y el mantenimiento del servidor.",
    "Create Schedule": "Crear Tarea Programada",
    "Create new schedule": "Crear nueva tarea programada",
    "A human readable identifier for this schedule.": "Un identificador legible por humanos para esta tarea programada.",
    "The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.": "El sistema de programación admite el uso de la sintaxis Cronjob al definir cuándo deben comenzar a ejecutarse las tareas. Utiliza los campos anteriores para especificar cuándo deben comenzar a ejecutarse estas tareas.",
    "Show Cheatsheet": "Mostrar Hoja de Trucos",
    "Show the cron cheatsheet for some examples.": "Mostrar la hoja de trucos de cron para algunos ejemplos.",
    "Only When Server Is Online": "Solo Cuando el Servidor Está En Línea",
    "Only execute this schedule when the server is in a running state.": "Solo ejecutar esta tarea programada cuando el servidor esté en estado de ejecución.",
    "Schedule Enabled": "Tarea Programada Habilitada",
    "This schedule will be executed automatically if enabled.": "Esta tarea programada se ejecutará automáticamente si está habilitada.",
    "Add New User": "Añadir Nuevo Usuario",
    "Grant other users access to your server with customizable permissions.": "Concede a otros usuarios acceso a tu servidor con permisos personalizables.",
    "No Users Found": "No Se Encontraron Usuarios",
    "Add users to your server to collaborate and share access with custom permissions.": "Añade usuarios a tu servidor para colaborar y compartir acceso con permisos personalizados.",
    "Empty": "Vacío",
    "Backups Unavailable": "Copias de Seguridad No Disponibles",
    "Backups cannot be created for this server because the backup limit is set to 0.": "No se pueden crear copias de seguridad para este servidor porque el límite de copias de seguridad está establecido en 0.",
    "Create New Subdomain": "Crear Nuevo Subdominio",
    "Choose a unique name for your subdomain": "Elige un nombre único para tu subdominio",
    "Create custom subdomains to provide easy access to your server. Instead of using IP addresses, your users can connect through friendly URLs.": "Crea subdominios personalizados para proporcionar un acceso fácil a tu servidor. En lugar de usar direcciones IP, tus usuarios pueden conectarse a través de URLs amigables.",
    "Create your first subdomain to get started with custom domain routing": "Crea tu primer subdominio para empezar con el enrutamiento de dominio personalizado",
    "No Subdomains Found": "No Se Encontraron Subdominios",
    "are automatically routed to your server": "se enrutan automáticamente a tu servidor",
    "Example subdomain:": "Ejemplo de subdominio:",
    "This is the command that will be executed when your server starts.": "Este es el comando que se ejecutará cuando se inicie tu servidor.",
    "This is an advanced feature allowing you a select a Docker image to use when running this server instance.": "Esta es una característica avanzada que te permite seleccionar una imagen Docker para usar al ejecutar esta instancia del servidor.",
    "Configura environment variables that control your server's behavior and settings.": "Configura variables de entorno que controlan el comportamiento y la configuración de tu servidor.",
    "Staffs can request an access a your server. If you accept it, staff can manage it. But you can deny it anytime.": "El personal puede solicitar acceso a tu servidor. Si lo aceptas, el personal puede gestionarlo. Pero puedes denegarlo en cualquier momento.",
    "There are no access requests for this server.": "No hay solicitudes de acceso para este servidor.",
    "SFTP Connection Details": "Detalles de Conexión SFTP",
    "Your SFTP password is the same as the password you use to access this panel.": "Tu contraseña SFTP es la misma que usas para acceder a este panel.",
    "Server identification and technical details": "Identificación del servidor y detalles técnicos",
    "Change Server Details": "Cambiar Detalles del Servidor",
    "Update your server name and description": "Actualiza el nombre y la descripción de tu servidor",
    "Reset your server to its original state": "Restablece tu servidor a su estado original",
    "Reinstalling your server will stop it, and then re-run the installation script that initially set it up.": "Reinstalar tu servidor lo detendrá y luego volverá a ejecutar el script de instalación que lo configuró inicialmente.",
    "Some files may be deleted or modified during this process, please back up your data before continuing.": "Algunos archivos pueden ser eliminados o modificados durante este proceso, por favor, haz una copia de seguridad de tus datos antes de continuar.",
    "Activity Timeline": "Cronología de Actividad",
    "No activity logs available for this server.": "No hay registros de actividad disponibles para este servidor.",
    "Server actions and events will appear here when they occur.": "Las acciones y eventos del servidor aparecerán aquí cuando ocurran.",
    "Server Suspended": "Servidor Suspendido",
    "Your free server has expired.": "Tu servidor gratuito ha expirado.",
    "Free Server Expired": "Servidor Gratuito Expirado",
    "Expired on:": "Expiró el:",
    "Renew your free server to continue playing!": "¡Renueva tu servidor gratuito para seguir jugando!",
    "Keep Your Server Alive!": "¡Mantén Tu Servidor Vivo!",
    "Watch a quick ad to keep your awesome server running!": "¡Mira un anuncio rápido para mantener tu increíble servidor funcionando!",
    "All times shown in": "Todas las horas mostradas en",
    "Get": "Obtener",
    "more hours": "más horas",
    "for FREE!": "¡GRATIS!",
    "Just watch a short ad and your server stays online!": "¡Solo mira un anuncio corto y tu servidor permanecerá en línea!",
    "Your Renewal Stats": "Tus Estadísticas de Renovación",
    "Renewals Today:": "Renovaciones Hoy:",
    "Next renewal ready:": "Próxima renovación lista:",
    "Renew my awesone server": "Renovar mi increíble servidor",
    "Server Always in Queue?": "¿Servidor Siempre en Cola?",
    "Move your server to a faster location!": "¡Mueve tu servidor a una ubicación más rápida!",
    "Try a Different Server Node!": "¡Prueba un Nodo de Servidor Diferente!",
    "Experiencing long queue times? Transfer your server to a different location for better performance!": "¿Experimentando largos tiempos de espera en la cola? ¡Transfiere tu servidor a una ubicación diferente para un mejor rendimiento!",
    "Important": "Importante",
    "Make a backup first!": "¡Haz una copia de seguridad primero!",
    "Quick Transfer": "Transferencia Rápida",
    "Choose Location": "Elegir Ubicación",
    "RAM Boost Power!": "¡Potencia de Aumento de RAM!",
    "Get extra RAM by watching a quick ad!": "¡Obtén RAM extra viendo un anuncio rápido!",
    "Current RAM": "RAM Actual",
    "Available Boosts": "Aumentos Disponibles",
    "boost available": "aumento disponible",
    "Choose from": "Elige de",
    "configuration": "configuración",
    "Select Boost": "Seleccionar Aumento",
    "Upgrade Your Server!": "¡Actualiza Tu Servidor!",
    "Get more RAM, CPU power, and storage space!": "¡Obtén más RAM, potencia de CPU y espacio de almacenamiento!",
    "Customize Your Server Resources": "Personaliza los Recursos de Tu Servidor",
    "Change your server's configuration to get more RAM, CPU, disk space, and other cool features!": "Cambia la configuración de tu servidor para obtener más RAM, CPU, espacio en disco y otras características geniales.",
    "Note": "Nota",
    "You'll need to restart your server after upgrading!": "¡Tendrás que reiniciar tu servidor después de actualizar!",
    "Upgrade Server!": "¡Actualizar Servidor!",
    "Never Miss a Renewal!": "¡Nunca Te Pierdas una Renovación!",
    "Get notified when your server needs attention!": "¡Recibe notificaciones cuando tu servidor necesite atención!",
    "Smart Notification System": "Sistema de Notificación Inteligente",
    "Get browser notifications and in-game messages when your server is about to expire!": "¡Recibe notificaciones del navegador y mensajes dentro del juego cuando tu servidor esté a punto de expirar!",
    "Never forget": "Nunca olvides",
    "Keep your server running 24/7!": "¡Mantén tu servidor funcionando 24/7!",
    "Setup Notifications": "Configurar Notificaciones",
    "Danger Zone": "Zona de Peligro",
    "Permanently delete your server and all data": "Elimina permanentemente tu servidor y todos los datos",
    "This action cannot be undone!": "¡Esta acción no se puede deshacer!",
    "Once deleted, your server and all its files will be gone forever. Make sure you have backups!": "Una vez eliminado, tu servidor y todos sus archivos desaparecerán para siempre. ¡Asegúrate de tener copias de seguridad!",
    "Delete Server Forever": "Eliminar Servidor Para Siempre",
    "This server has been suspended.": "Este servidor ha sido suspendido.",
    "You need a renew it to continue using it.": "Necesitas renovarlo para seguir usándolo.",
    "Page Not Found - Access Denied": "Página No Encontrada - Acceso Denegado"
}

